site_name: Sharing developer experiences
site_author: Gualtiero Testa
site_url: https://gualtierotesta.github.io/blog

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - navigation.instant

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-Z08MZGHK67

nav:
  - "Home": index.md
  - "About me": about.md
  - "Articles": articles/index.md
  - "Books reviews": books/index.md
  - "Certifications": certifications/index.md
  - "Languages": languages/index.md
  - "Methodologies": methodologies/index.md
  - "Security": security/index.md
  - "My books": my-books.md
  - "Tools": tools/index.md
